#!/usr/bin/env bash
set -ex

npm install

node_modules/.bin/faucet

VERSION=$(npm view innoq-bootstrap-theme version)

mkdir -p dist/css/$VERSION
cp dist/css/innoq-bootstrap-theme.css dist/css/$VERSION/innoq-bootstrap-theme.css
zip -r innoq-bootstrap-theme-$VERSION.zip src/ dist/ package.json README.md LICENSE
