#!/usr/bin/env bash
set -ex

npm install && npm run compile

cd bootstrap

npm install

npm run dist

export HUGO_ENV="development" # turn off file integrity checks, before building the documentation

npm run docs-build

cp ../dist/css/innoq-bootstrap-theme.css _site/docs/5.1/dist/css/bootstrap.css

cd _site

live-server .
