#!/usr/bin/env bash
set -ex

node_modules/.bin/faucet

# TODO: Generate Bootstrap docs and serve locally
cd bootstrap

npm install

bundle install

npm run docs

mkdir -p ../documentation

cp -R _gh_pages/* ../documentation

cd ..

cp dist/css/innoq-bootstrap-theme.css documentation/docs/4.5/dist/css/bootstrap.css
