#!/usr/bin/env bash
set -ex

node_modules/.bin/faucet

# TODO: Generate Bootstrap docs and serve locally
cd bootstrap

npm install

npm run dist

export HUGO_ENV="development" # turn off file integrity checks, before building the documentation

npm run docs-build

mkdir -p ../documentation

cp -R _site/* ../documentation

cd ..

cp dist/css/innoq-bootstrap-theme.css documentation/docs/5.1/dist/css/bootstrap.css
