name: Deploy to INNOQ CDN

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
    tags:
      - v*  # Our tags are prefixed with 'v'
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: |
        npm install
        npm run dist

    - name: Configure AWS credentials from INNOQ account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Copy files from dist to INNOQ asset bucket
      run: |
        aws s3 sync ./dist ${{ secrets.AWS_BUCKET_NAME }} --acl public-read
